import AsyncStorage from '@react-native-async-storage/async-storage';

async function pegarIdioma() {
    const escolha = await AsyncStorage.getItem('idioma');

    let cadastro = [];
    let login = [];
    let pais = [];
    let aviso = [];
    let questionario = [];
    let bar = [];
    let perfil = [];
    let cores = [];
    let endereco = [];
    let enderecoAviso = [];
    let home = [];
    let feed = [];
    let documentos = [];
    let docs = [];
    let Mapa = [];
    let termos = [];
    let privacidade = [];

    switch (escolha) {
        case 'Portugues':
            Mapa = [
                //Loading 
                'Obtendo sua localização...',

                //Principal
                'Locais Próximos ',
                'Todos os Locais Próximos',
                'Poupatempo Próximos',
                'SPTrans Próximos',

                //modal de informações do local 

                'Distância da sua localização:',
                'Endereço:',
                'Horário de Funcionamento:',
                'Coordenadas:',
                'Serviços Disponíveis:',
                ' • Emissão de RG',
                'Carteira de Trabalho',
                'Serviços do Detran',
                'Outros serviços governamentais',
                'Recarga de Bilhete Único',
                'Emissão de cartões',
                'Informações sobre linhas',
                'Outros serviços de transporte',
                'Como Chegar',

            ]
            cadastro = [
                'Cadastre-se',
                'Nome',
                'Email',
                'País de Origem',
                'Data de nascimento',
                'Crie uma senha',
                'Criar Conta',
                'Já tem conta?',
                'Clique aqui',
                'Telefone',
                'Atualizar Perfil',
                'Salvar Alterações',
                'Carregando'
            ];
            login = [
                'Bem-Vindo de volta!',
                'Digite o seu email:',
                'Digite a sua senha:',
                'Entrar',
                'Não tem uma conta?',
                'Crie uma agora'
            ];
            pais = [
                'Afeganistão', 'África do Sul', 'Albânia', 'Alemanha', 'Andorra',
                'Angola', 'Anguilla', 'Antártida', 'Antígua e Barbuda', 'Arábia Saudita',
                'Argélia', 'Argentina', 'Armênia', 'Aruba', 'Austrália',
                'Áustria', 'Azerbaijão', 'Bahamas', 'Bahrein', 'Bangladesh',
                'Barbados', 'Bélgica', 'Belize', 'Benim', 'Bermudas',
                'Bielorrússia', 'Bolívia, Estado Plurinacional da', 'Bonaire, Santo Eustáquio e Saba', 'Bósnia e Herzegovina', 'Botsuana',
                'Brasil', 'Brunei Darussalam', 'Bulgária', 'Burkina Faso', 'Burundi',
                'Butão', 'Cabo Verde', 'Camboja', 'Camarões', 'Canadá',
                'Catar', 'Cazaquistão', 'Chade', 'Chile', 'China',
                'Chipre', 'Colômbia', 'Comores', 'Congo', 'Congo, República Democrática do',
                'Coreia do Sul', 'Coreia do Norte', 'Costa do Marfim', 'Costa Rica', 'Croácia',
                'Cuba', 'Curaçau', 'Djibuti', 'Dominica', 'Egito',
                'El Salvador', 'Emirados Árabes Unidos', 'Equador', 'Eritreia', 'Eslováquia',
                'Eslovênia', 'Espanha', 'Essuatíni', 'Estados Unidos', 'Estônia',
                'Etiópia', 'Federação Russa', 'Fiji', 'Filipinas', 'Finlândia',
                'França', 'Gabão', 'Gâmbia', 'Gana', 'Geórgia',
                'Geórgia do Sul e Ilhas Sandwich do Sul', 'Gibraltar', 'Granada', 'Groenlândia', 'Guadalupe',
                'Guam', 'Guatemala', 'Guernsey', 'Guiana', 'Guiana Francesa',
                'Guiné', 'Guiné Equatorial', 'Guiné-Bissau', 'Haiti', 'Honduras',
                'Hong Kong', 'Hungria', 'Iêmen', 'Ilha Bouvet', 'Ilha Christmas',
                'Ilha de Man', 'Ilha Heard e Ilhas McDonald', 'Ilha Norfolk', 'Ilhas Åland', 'Ilhas Cayman',
                'Ilhas Cocos (Keeling)', 'Ilhas Cook', 'Ilhas Falkland (Malvinas)', 'Ilhas Marianas do Norte', 'Ilhas Marshall',
                'Ilhas Menores Distantes dos Estados Unidos', 'Ilhas Salomão', 'Ilhas Turcas e Caicos', 'Ilhas Virgens Americanas', 'Ilhas Virgens Britânicas',
                'Índia', 'Indonésia', 'Iraque', 'Irã, República Islâmica do', 'Irlanda',
                'Islândia', 'Israel', 'Itália', 'Jamaica', 'Japão',
                'Jersey', 'Jordânia', 'Kiribati', 'Kosovo', 'Kuwait',
                'Laos, República Democrática Popular do', 'Lesoto', 'Letônia', 'Líbano', 'Libéria',
                'Líbia', 'Liechtenstein', 'Lituânia', 'Luxemburgo', 'Macau',
                'Macedônia do Norte', 'Madagascar', 'Malaui', 'Malásia', 'Maldivas',
                'Mali', 'Malta', 'Marrocos', 'Martinica', 'Maurício',
                'Mauritânia', 'Mayotte', 'México', 'Micronésia, Estados Federados da', 'Mianmar',
                'Moldávia, República da', 'Mônaco', 'Mongólia', 'Montenegro', 'Montserrat',
                'Moçambique', 'Namíbia', 'Nauru', 'Nepal', 'Nicarágua',
                'Níger', 'Nigéria', 'Niue', 'Noruega', 'Nova Caledônia',
                'Nova Zelândia', 'Omã', 'Países Baixos', 'Paquistão', 'Palau',
                'Palestina, Estado da', 'Panamá', 'Papua Nova Guiné', 'Paraguai', 'Peru',
                'Pitcairn', 'Polinésia Francesa', 'Polônia', 'Porto Rico', 'Portugal',
                'Quênia', 'Quirguistão', 'Reino Unido', 'República Árabe da Síria', 'República Centro-Africana',
                'República Dominicana', 'Reunião', 'Romênia', 'Ruanda', 'Saara Ocidental',
                'Samoa', 'Samoa Americana', 'San Marino', 'Santa Helena, Ascensão e Tristão da Cunha', 'Santa Lúcia',
                'Santa Sé (Estado da Cidade do Vaticano)', 'São Bartolomeu', 'São Cristóvão e Neves', 'São Martinho (parte francesa)', 'São Martinho (parte holandesa)',
                'São Pedro e Miquelon', 'São Tomé e Príncipe', 'São Vicente e Granadinas', 'Senegal', 'Serra Leoa',
                'Sérvia', 'Seychelles', 'Singapura', 'Somália', 'Sri Lanka',
                'Sudão', 'Sudão do Sul', 'Suécia', 'Suíça', 'Suriname',
                'Svalbard e Jan Mayen', 'Tailândia', 'Taiwan, Província da China', 'Tajiquistão', 'Tanzânia, República Unida da',
                'Território Britânico do Oceano Índico', 'Territórios Franceses do Sul', 'Timor-Leste', 'Togo', 'Tokelau',
                'Tonga', 'Trindade e Tobago', 'Tunísia', 'Turcomenistão', 'Turquia',
                'Tuvalu', 'Ucrânia', 'Uganda', 'Uruguai', 'Uzbequistão',
                'Vanuatu', 'Venezuela', 'Vietnã', 'Wallis e Futuna', 'Zâmbia',
                'Zimbábue'
            ];
            aviso = [
                'O nome deve ter no mínimo 2 letras.',
                'Coloque uma data válida no formato dd/mm/aaaa.',
                'Email inválido. Antes do @ deve ter ao menos 6 caracteres e 1 letra; após o @ deve conter um ponto.',
                'A senha deve ter no mínimo 8 caracteres.',
                'Preencha o campo corretamente ou deixe em branco.',
                'Preencha email e senha!',
                'Email ou senha inválidos!',
                'Conta não encontrada',
                'Atenção'
            ];
            questionario = [
                'Digite o número da CRNM ou RNE',
                '*********',
                'Digite o número do CPF',
                '***.***.***-**',
                'Digite o número do Documento de Identificação do Mercosul',
                '************',
                'Digite o número do Passaporte',
                'AA******',
                'Concluir',
                'Questionário',
                'Informe aqui seus documentos de identificação. Não se preocupe, se não tiver algum, basta deixar em branco.',
                'Qual sua condição atual?',
                'Refugiado',
                'Imigrante'
            ];
            bar = ['Início', 'Notícias', 'Documentos', 'Perfil', 'Serviços'];
            perfil = [
                'Trocar idioma',
                'Temas',
                'Bolha:',
                'Ativada',
                'Desativada',
                'Termos de Uso',
                'Política de privacidade',
                'Sair da conta',
                'Editar Perfil',
                'Automático',
                'Claro',
                'Escuro',
                'Cor',
                'Modos',
                'Cores',
                'Alterar senha',
                'Cadastrar Endereço',
                'Atualizar Endereço',
                'Carregando...',
                'Erro',
                'Atenção',
                'Sucesso',
                '✅ Sucesso',
                'Foto de perfil atualizada!',
                '⚠️ Aviso',
                'Foto salva localmente, mas não foi possível sincronizar com o servidor',
                'Erro ao acessar a galeria!',
                'Permissão para acessar a galeria negada!',
                'Erro',
                'Usuário não identificado',
                'A imagem selecionada é inválida',
                'Enviando código...',
                'Digite o código enviado',
                'Digite o código de 5 dígitos',
                'Código incorreto!',
                'Cancelar',
                'Verificar',
                'Troque a senha',
                'Digite sua nova senha',
                'Confirme sua senha',
                'Atualizar Senha',
                'As senhas não coincidem',
                'Meu Perfil',
                'Ver Perfil',
                'Nome',
                'Email',
                'Telefone',
                'Não informado',
                'Endereço',
                'Excluir Perfil',
                'Excluir Perfil',
                'Tem certeza que deseja excluir sua conta? Esta ação não pode ser desfeita.',
                'Cancelar',
                'Excluir',
                'Sucesso',
                'Perfil excluído com sucesso',
                'Erro',
                'Não foi possível excluir o perfil',
                'Erro',
                'Não foi possível fazer logout.',
                'Endereço',
                'Ajuda',
                'Documentos'
            ];
            cores = ['Padrão', 'Laranja', 'Azul', 'Roxo', 'Amarelo', 'Rosa', 'Vermelho', 'Verde', 'Azul Escuro'];
            endereco = [
                'Cadastrar endereço',
                'CEP',
                'Logradouro',
                'Número',
                'Bairro',
                'Cidade',
                'Estado',
            ];
            enderecoAviso = [
                '⚠️ CEP inválido. Digite um CEP válido no formato 12345-678',
                '⚠️ Logradouro inválido. Digite um logradouro válido',
                '⚠️ Número inválido. Digite o número do endereço',
                '⚠️ Bairro inválido. Digite um bairro válido',
                '⚠️ Cidade inválida. Digite uma cidade válida',
                '✅ Dados atualizados com sucesso!',
                '❌ Erro ao salvar alterações',
                '❌ CEP não encontrado. Verifique o CEP digitado e tente novamente.',
                '❌ Erro ao buscar o CEP. Verifique sua conexão.'
            ];
            home = [
                'Passe de Ônibus',
                'Carteira de Motorista',
                'Passaporte',
                'Comprovante de Endereço',
                'Mercosul',
                'Título de Eleitor',
                'Olá',
                'Sistema de Saúde',
                'Documentos de Identificação',
                'Números de Emergência',
                'Locais Importantes',
                'Cadastre o seu endereço para que possamos te ajudar melhor!'
            ];
            feed = [
                'Pesquisar notícias...',
                'resultado(s) encontrado(s) para',
                'Nenhuma notícia encontrada para',
                'Tente pesquisar por outras palavras-chave',
                'Grade',
                'Linha',
                'Ler notícia completa',
                'Notícia',
                'Carregando Notícias...'
            ];
            documentos = [
                'Numeros de Emergência',
                'Documentos de Identificação',
                'Locais Importantes',
                'Sistema de Saúde',
                'Documentos de Trabalho',
                'Transporte Público',
                'Veiculos e Habilitação',
                'Abrigos',
                'Direitos do Imigrante',
                'Deveres do Imigrante',
            ];
            docs = [
                'Imagem:',
                'Descrição:',
                'Campos Principais:',
                'Validade:',
                'Uso Comum:',
                'Tipos disponíveis:',
                'Fechar',
                'Requisitos:',
                'Erro ao carregar os documentos.',
                'Nenhum documento disponível.',
                'Local:'
            ];
            termos = [
                'Termos de Uso',
                '1. Aceitação dos Termos',
                'Ao utilizar nossos serviços, você concorda com estes termos de uso.',
                'Estes termos regem o uso do aplicativo e todos os serviços relacionados.',
                '2. Uso do Serviço',
                'Você concorda em usar o serviço apenas para fins legais e de acordo com estes termos.',
                'É proibido utilizar o serviço para atividades ilegais ou não autorizadas.',
                '3. Conta do Usuário',
                'Você é responsável por manter a confidencialidade de sua conta e senha.',
                'Todas as atividades realizadas em sua conta são de sua responsabilidade.',
                '4. Propriedade Intelectual',
                'Todo o conteúdo do aplicativo, incluindo textos, gráficos, logos e software,',
                'é propriedade da empresa e protegido por leis de direitos autorais.',
                '5. Limitação de Responsabilidade',
                'Não nos responsabilizamos por danos indiretos, incidentais ou consequenciais',
                'resultantes do uso ou incapacidade de usar nossos serviços.',
                '6. Modificações dos Termos',
                'Reservamo-nos o direito de modificar estes termos a qualquer momento.',
                'Alterações significativas serão notificadas aos usuários.',
                '7. Lei Aplicável',
                'Estes termos são regidos pelas leis do país onde a empresa tem sua sede principal.',
                '8. Contato',
                'Para questões sobre estes termos, entre em contato através do suporte do aplicativo.',
                'Entendi'
            ];

            privacidade = [
                'Política de Privacidade',
                '1. Coleta de Informações',
                'Coletamos informações que você nos fornece diretamente, como nome,',
                'email, telefone e documentos quando necessário para os serviços.',
                '2. Uso das Informações',
                'Utilizamos suas informações para:',
                '• Fornecer e melhorar nossos serviços',
                '• Personalizar sua experiência',
                '• Enviar notificações importantes',
                '• Cumprir obrigações legais',
                '3. Compartilhamento de Dados',
                'Não vendemos suas informações pessoais. Podemos compartilhar dados com:',
                '• Prestadores de serviços essenciais',
                '• Autoridades legais quando exigido por lei',
                '• Novos proprietários em caso de fusão ou aquisição',
                '4. Segurança dos Dados',
                'Implementamos medidas de segurança técnicas e organizacionais para',
                'proteger suas informações contra acesso não autorizado ou divulgação.',
                '5. Seus Direitos',
                'Você tem o direito de:',
                '• Acessar suas informações pessoais',
                '• Corrigir dados imprecisos',
                '• Solicitar a exclusão de seus dados',
                '• Opor-se ao processamento de dados',
                '6. Retenção de Dados',
                'Mantemos suas informações apenas pelo tempo necessário para cumprir',
                'as finalidades descritas nesta política ou exigidas por lei.',
                '7. Alterações na Política',
                'Podemos atualizar esta política periodicamente. Notificaremos sobre',
                'mudanças significativas através do aplicativo ou por email.',
                '8. Contato',
                'Para exercer seus direitos ou dúvidas sobre privacidade,',
                'entre em contato com nosso encarregado de proteção de dados.',
                'Entendi'
            ];
            break;

        case 'Inglês':
            Mapa = [
                // Loading
                'Getting your location...',

                // Main
                'Nearby Places',
                'All Nearby Places',
                'Nearby Poupatempo',
                'Nearby SPTrans',

                // Modal with location information
                'Distance from your location:',
                'Address:',
                'Opening Hours:',
                'Coordinates:',
                'Available Services:',
                ' • ID Issuance',
                'Work Card',
                'Detran Services',
                'Other government services',
                'Recharge of Bilhete Único',
                'Card Issuance',
                'Information about lines',
                'Other transportation services',
                'How to get there',
            ];
            cadastro = [
                'Sign Up',
                'Name',
                'Email',
                'Country of Origin',
                'Date of Birth',
                'Create a Password',
                'Create Account',
                'Already have an account?',
                'Click here',
                'Phone',
                'Update Profile',
                'Save Changes',
                'Loading',
            ];
            login = [
                'Welcome back!',
                'Enter your email:',
                'Enter your password:',
                'Sign in',
                "Don't have an account?",
                'Create one now'
            ];
            pais = [
                'Afghanistan', 'South Africa', 'Albania', 'Germany', 'Andorra',
                'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Saudi Arabia',
                'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Australia',
                'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
                'Barbados', 'Belgium', 'Belize', 'Benin', 'Bermuda',
                'Belarus', 'Bolivia, Plurinational State of', 'Bonaire, Sint Eustatius and Saba', 'Bosnia and Herzegovina', 'Botswana',
                'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
                'Bhutan', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
                'Qatar', 'Kazakhstan', 'Chad', 'Chile', 'China',
                'Cyprus', 'Colombia', 'Comoros', 'Congo', 'Congo, Democratic Republic of the',
                'Korea, Republic of', 'Korea, Democratic People\'s Republic of', 'Côte d\'Ivoire', 'Costa Rica', 'Croatia',
                'Cuba', 'Curaçao', 'Djibouti', 'Dominica', 'Egypt',
                'El Salvador', 'United Arab Emirates', 'Ecuador', 'Eritrea', 'Slovakia',
                'Slovenia', 'Spain', 'Eswatini', 'United States', 'Estonia',
                'Ethiopia', 'Russian Federation', 'Fiji', 'Philippines', 'Finland',
                'France', 'Gabon', 'Gambia', 'Ghana', 'Georgia',
                'South Georgia and the South Sandwich Islands', 'Gibraltar', 'Grenada', 'Greenland', 'Guadeloupe',
                'Guam', 'Guatemala', 'Guernsey', 'Guyana', 'French Guiana',
                'Guinea', 'Equatorial Guinea', 'Guinea-Bissau', 'Haiti', 'Honduras',
                'Hong Kong', 'Hungary', 'Yemen', 'Bouvet Island', 'Christmas Island',
                'Isle of Man', 'Heard Island and McDonald Islands', 'Norfolk Island', 'Åland Islands', 'Cayman Islands',
                'Cocos (Keeling) Islands', 'Cook Islands', 'Falkland Islands (Malvinas)', 'Northern Mariana Islands', 'Marshall Islands',
                'United States Minor Outlying Islands', 'Solomon Islands', 'Turks and Caicos Islands', 'United States Virgin Islands', 'British Virgin Islands',
                'India', 'Indonesia', 'Iraq', 'Iran, Islamic Republic of', 'Ireland',
                'Iceland', 'Israel', 'Italy', 'Jamaica', 'Japan',
                'Jersey', 'Jordan', 'Kiribati', 'Kosovo', 'Kuwait',
                'Lao People\'s Democratic Republic', 'Lesotho', 'Latvia', 'Lebanon', 'Liberia',
                'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao',
                'North Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
                'Mali', 'Malta', 'Morocco', 'Martinique', 'Mauritius',
                'Mauritania', 'Mayotte', 'Mexico', 'Micronesia, Federated States of', 'Myanmar',
                'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat',
                'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Nicaragua',
                'Niger', 'Nigeria', 'Niue', 'Norway', 'New Caledonia',
                'New Zealand', 'Oman', 'Netherlands', 'Pakistan', 'Palau',
                'Palestine, State of', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
                'Pitcairn', 'French Polynesia', 'Poland', 'Puerto Rico', 'Portugal',
                'Kenya', 'Kyrgyzstan', 'United Kingdom', 'Syrian Arab Republic', 'Central African Republic',
                'Dominican Republic', 'Réunion', 'Romania', 'Rwanda', 'Western Sahara',
                'Samoa', 'American Samoa', 'San Marino', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Lucia',
                'Holy See (Vatican City State)', 'Saint Barthélemy', 'Saint Kitts and Nevis', 'Saint Martin (French part)', 'Sint Maarten (Dutch part)',
                'Saint Pierre and Miquelon', 'Sao Tome and Principe', 'Saint Vincent and the Grenadines', 'Senegal', 'Sierra Leone',
                'Serbia', 'Seychelles', 'Singapore', 'Somalia', 'Sri Lanka',
                'Sudan', 'South Sudan', 'Sweden', 'Switzerland', 'Suriname',
                'Svalbard and Jan Mayen', 'Thailand', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of',
                'British Indian Ocean Territory', 'French Southern Territories', 'Timor-Leste', 'Togo', 'Tokelau',
                'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Turkey',
                'Tuvalu', 'Ukraine', 'Uganda', 'Uruguay', 'Uzbekistan',
                'Vanuatu', 'Venezuela, Bolivarian Republic of', 'Vietnam', 'Wallis and Futuna', 'Zambia',
                'Zimbabwe'
            ],
                aviso = [
                    'The name must have at least 2 letters.',
                    'Enter a valid date in the format dd/mm/yyyy.',
                    'Invalid email. Before the @ must have at least 6 characters and 1 letter; after the @ it must contain a dot.',
                    'The password must be at least 8 characters long.',
                    'Fill in the field correctly or leave it blank.',
                    'Fill in email and password!',
                    'Invalid email or password!',
                    'Account not found',
                    'Attention'
                ];
            questionario = [
                'Enter the CRNM or RNE number',
                '*********',
                'Enter the CPF number',
                '***.***.***-**',
                'Enter the Mercosur Identification Document number',
                '************',
                'Enter the Passport number',
                'AA******',
                'Finish',
                'Questionnaire',
                'Enter your identification documents here. Don’t worry, if you don’t have any, just leave it blank.',
                'What is your current status?',
                'Refugee',
                'Immigrant'
            ];
            bar = ['Home', 'News', 'Documents', 'Profile', 'Services'];
            perfil = [
                'Change language',
                'Themes',
                'Notifications:',
                'Enabled',
                'Disabled',
                'Terms of Use',
                'Privacy Policy',
                'Log out',
                'Edit Profile',
                'Automatic',
                'Light',
                'Dark',
                'Color',
                'Modes',
                'Colors',
                'Change Password',
                'Register Address',
                'Update Address',
                'Loading...',
                'Error',
                'Attention',
                'Success',
                '✅ Success',
                'Profile picture updated!',
                '⚠️ Warning',
                'Photo saved locally, but could not sync with the server',
                'Error accessing gallery!',
                'Permission to access gallery denied!',
                'Error',
                'User not identified',
                'The selected image is invalid',
                'Sending code...',
                'Enter the code sent',
                'Enter the 5-digit code',
                'Incorrect code!',
                'Cancel',
                'Verify',
                'Change your password',
                'Enter your new password',
                'Confirm your password',
                'Update Password',
                'Passwords do not match',
                'My Profile',
                'View Profile',
                'Name',
                'Email',
                'Phone',
                'Not provided',
                'Address',
                'Delete Profile',
                'Delete Profile',
                'Are you sure you want to delete your account? This action cannot be undone.',
                'Cancel',
                'Delete',
                'Success',
                'Profile deleted successfully',
                'Error',
                'Could not delete profile',
                'Error',
                'Could not log out.',
                'Address',
                'Help',
                'Documents'
            ];

            cores = ['Default', 'Orange', 'Blue', 'Purple', 'Yellow', 'Pink', 'Red', 'Green', 'Dark Blue'];
            endereco = [
                'Register address',
                'ZIP',
                'Street',
                'Number',
                'Neighborhood',
                'City',
                'State'
            ];
            enderecoAviso = [
                '⚠️ Invalid ZIP. Enter a valid ZIP in the format 12345-678',
                '⚠️ Invalid street. Enter a valid street',
                '⚠️ Invalid number. Enter the address number',
                '⚠️ Invalid neighborhood. Enter a valid neighborhood',
                '⚠️ Invalid city. Enter a valid city',
                '✅ Data updated successfully!',
                '❌ Error saving changes',
                '❌ ZIP not found. Check the ZIP entered and try again.',
                '❌ Error fetching ZIP. Check your connection.'
            ];
            home = [
                'Bus Pass',
                'Driver’s License',
                'Passport',
                'Proof of Address',
                'Mercosur',
                'Voter ID',
                'Hello',
                'Health System',
                'Identification Documents',
                'Emergency Numbers',
                'Important Locations',
                'Register your address so we can help you better!'
            ];
            feed = [
                'Search news...',
                'result(s) found for',
                'No news found for',
                'Try searching for other keywords',
                'Grid',
                'Line',
                'Read full news',
                'News',
                'Loading News...'
            ];
            documentos = [
                'Emergency Numbers',
                'Identification Documents',
                'Important Locations',
                'Health System',
                'Work Documents',
                'Public Transportation',
                'Vehicles and Licenses',
                'Shelters',
                'Immigrant Rights',
                'Immigrant Duties'
            ];
            docs = [
                'Image:',
                'Description:',
                'Main Fields:',
                'Validity:',
                'Common Use:',
                'Available Types:',
                'Close',
                'Requirements:',
                'Error loading documents.',
                'No documents available.',
                'Location:'
            ];
            termos = [
                'Terms of Use',
                '1. Acceptance of the Terms',
                'By using our services, you agree to these terms of use.',
                'These terms govern the use of the application and all related services.',
                '2. Use of the Service',
                'You agree to use the service only for lawful purposes and in accordance with these terms.',
                'It is prohibited to use the service for illegal or unauthorized activities.',
                '3. User Account',
                'You are responsible for maintaining the confidentiality of your account and password.',
                'All activities performed under your account are your responsibility.',
                '4. Intellectual Property',
                'All content in the application, including texts, graphics, logos, and software,',
                'is the property of the company and protected by copyright laws.',
                '5. Limitation of Liability',
                'We are not responsible for indirect, incidental, or consequential damages',
                'resulting from the use or inability to use our services.',
                '6. Modifications to the Terms',
                'We reserve the right to modify these terms at any time.',
                'Significant changes will be notified to users.',
                '7. Governing Law',
                'These terms are governed by the laws of the country where the company has its main headquarters.',
                '8. Contact',
                'For questions about these terms, contact us through the app support.',
                'Got it'
            ];
            privacidade = [
                'Privacy Policy',
                '1. Information Collection',
                'We collect information you provide directly to us, such as name,',
                'email, phone number, and documents when necessary for the services.',
                '2. Use of Information',
                'We use your information to:',
                '• Provide and improve our services',
                '• Personalize your experience',
                '• Send important notifications',
                '• Comply with legal obligations',
                '3. Data Sharing',
                'We do not sell your personal information. We may share data with:',
                '• Essential service providers',
                '• Legal authorities when required by law',
                '• New owners in case of merger or acquisition',
                '4. Data Security',
                'We implement technical and organizational security measures to',
                'protect your information against unauthorized access or disclosure.',
                '5. Your Rights',
                'You have the right to:',
                '• Access your personal information',
                '• Correct inaccurate data',
                '• Request the deletion of your data',
                '• Object to data processing',
                '6. Data Retention',
                'We keep your information only for as long as necessary to fulfill',
                'the purposes described in this policy or as required by law.',
                '7. Policy Changes',
                'We may update this policy periodically. Significant changes will be',
                'notified through the app or via email.',
                '8. Contact',
                'To exercise your rights or for privacy-related questions,',
                'contact our data protection officer.',
                'Got it'
            ];



            break;

        case 'Espanhol':
            Mapa = [
                // Cargando
                'Obteniendo tu ubicación...',

                // Principal
                'Lugares Cercanos',
                'Todos los Lugares Cercanos',
                'Poupatempo Cercanos',
                'SPTrans Cercanos',

                // Modal con información del lugar
                'Distancia desde tu ubicación:',
                'Dirección:',
                'Horario de Atención:',
                'Coordenadas:',
                'Servicios Disponibles:',
                ' • Emisión de DNI',
                'Carnet de Trabajo',
                'Servicios del Detran',
                'Otros servicios gubernamentales',
                'Recarga de Billete Único',
                'Emisión de tarjetas',
                'Información sobre líneas',
                'Otros servicios de transporte',
                'Cómo llegar',
            ];

            cadastro = [
                'Regístrate',
                'Nombre',
                'Correo electrónico',
                'País de Origen',
                'Fecha de Nacimiento',
                'Crea una contraseña',
                'Crear Cuenta',
                '¿Ya tienes cuenta?',
                'Haz clic aquí',
                'Teléfono',
                'Actualizar Perfil',
                'Guardar Cambios',
                'Cargando'
            ];
            login = [
                '¡Bienvenido de nuevo!',
                'Ingrese su correo electrónico:',
                'Ingrese su contraseña:',
                'Entrar',
                '¿No tienes una cuenta?',
                'Crea una ahora'
            ];
            pais = [
                'Afganistán', 'Sudáfrica', 'Albania', 'Alemania', 'Andorra',
                'Angola', 'Anguila', 'Antártida', 'Antigua y Barbuda', 'Arabia Saudita',
                'Argelia', 'Argentina', 'Armenia', 'Aruba', 'Australia',
                'Austria', 'Azerbaiyán', 'Bahamas', 'Baréin', 'Bangladés',
                'Barbados', 'Bélgica', 'Belice', 'Benín', 'Bermudas',
                'Bielorrusia', 'Bolivia, Estado Plurinacional de', 'Bonaire, San Eustaquio y Saba', 'Bosnia y Herzegovina', 'Botsuana',
                'Brasil', 'Brunéi Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
                'Bután', 'Cabo Verde', 'Camboya', 'Camerún', 'Canadá',
                'Catar', 'Kazajistán', 'Chad', 'Chile', 'China',
                'Chipre', 'Colombia', 'Comoras', 'Congo', 'Congo, República Democrática del',
                'Corea, República de', 'Corea, República Popular Democrática de', 'Costa de Marfil', 'Costa Rica', 'Croacia',
                'Cuba', 'Curazao', 'Yibuti', 'Dominica', 'Egipto',
                'El Salvador', 'Emiratos Árabes Unidos', 'Ecuador', 'Eritrea', 'Eslovaquia',
                'Eslovenia', 'España', 'Esuatini', 'Estados Unidos', 'Estonia',
                'Etiopía', 'Federación Rusa', 'Fiyi', 'Filipinas', 'Finlandia',
                'Francia', 'Gabón', 'Gambia', 'Ghana', 'Georgia',
                'Georgia del Sur e Islas Sandwich del Sur', 'Gibraltar', 'Granada', 'Groenlandia', 'Guadalupe',
                'Guam', 'Guatemala', 'Guernsey', 'Guyana', 'Guayana Francesa',
                'Guinea', 'Guinea Ecuatorial', 'Guinea-Bisáu', 'Haití', 'Honduras',
                'Hong Kong', 'Hungría', 'Yemen', 'Isla Bouvet', 'Isla de Navidad',
                'Isla de Man', 'Isla Heard e Islas McDonald', 'Isla Norfolk', 'Islas de Åland', 'Islas Caimán',
                'Islas Cocos (Keeling)', 'Islas Cook', 'Islas Malvinas', 'Islas Marianas del Norte', 'Islas Marshall',
                'Islas Ultramarinas Menores de Estados Unidos', 'Islas Salomón', 'Islas Turcas y Caicos', 'Islas Vírgenes de los Estados Unidos', 'Islas Vírgenes Británicas',
                'India', 'Indonesia', 'Irak', 'Irán, República Islámica de', 'Irlanda',
                'Islandia', 'Israel', 'Italia', 'Jamaica', 'Japón',
                'Jersey', 'Jordania', 'Kiribati', 'Kosovo', 'Kuwait',
                'Laos, República Democrática Popular de', 'Lesoto', 'Letonia', 'Líbano', 'Liberia',
                'Libia', 'Liechtenstein', 'Lituania', 'Luxemburgo', 'Macao',
                'Macedonia del Norte', 'Madagascar', 'Malaui', 'Malasia', 'Maldivas',
                'Mali', 'Malta', 'Marruecos', 'Martinica', 'Mauricio',
                'Mauritania', 'Mayotte', 'México', 'Micronesia, Estados Federados de', 'Birmania',
                'Moldavia, República de', 'Mónaco', 'Mongolia', 'Montenegro', 'Montserrat',
                'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Nicaragua',
                'Níger', 'Nigeria', 'Niue', 'Noruega', 'Nueva Caledonia',
                'Nueva Zelanda', 'Omán', 'Países Bajos', 'Pakistán', 'Palaos',
                'Palestina, Estado de', 'Panamá', 'Papúa Nueva Guinea', 'Paraguay', 'Perú',
                'Pitcairn', 'Polinesia Francesa', 'Polonia', 'Puerto Rico', 'Portugal',
                'Kenia', 'Kirguistán', 'Reino Unido', 'República Árabe Siria', 'República Centroafricana',
                'República Dominicana', 'Reunión', 'Rumania', 'Ruanda', 'Sáhara Occidental',
                'Samoa', 'Samoa Americana', 'San Marino', 'Santa Elena, Ascensión y Tristán de Acuña', 'Santa Lucía',
                'Santa Sede (Estado de la Ciudad del Vaticano)', 'San Bartolomé', 'San Cristóbal y Nieves', 'San Martín (parte francesa)', 'Sint Maarten (parte neerlandesa)',
                'San Pedro y Miquelón', 'Santo Tomé y Príncipe', 'San Vicente y las Granadinas', 'Senegal', 'Sierra Leona',
                'Serbia', 'Seychelles', 'Singapur', 'Somalia', 'Sri Lanka',
                'Sudán', 'Sudán del Sur', 'Suecia', 'Suiza', 'Surinam',
                'Svalbard y Jan Mayen', 'Tailandia', 'Taiwán, Provincia de China', 'Tayikistán', 'Tanzania, República Unida de',
                'Territorio Británico del Océano Índico', 'Tierras Australes y Antárticas Francesas', 'Timor Oriental', 'Togo', 'Tokelau',
                'Tonga', 'Trinidad y Tobago', 'Túnez', 'Turkmenistán', 'Turquía',
                'Tuvalu', 'Ucrania', 'Uganda', 'Uruguay', 'Uzbekistán',
                'Vanuatu', 'Venezuela, República Bolivariana de', 'Vietnam', 'Wallis y Futuna', 'Zambia',
                'Zimbabue'
            ]
            aviso = [
                'El nombre debe tener al menos 2 letras.',
                'Ingrese una fecha válida en el formato dd/mm/aaaa.',
                'Correo electrónico inválido. Antes del @ debe tener al menos 6 caracteres y 1 letra; después del @ debe contener un punto.',
                'La contraseña debe tener al menos 8 caracteres.',
                'Complete el campo correctamente o déjelo en blanco.',
                '¡Ingrese correo y contraseña!',
                '¡Correo electrónico o contraseña inválidos!',
                'Cuenta no encontrada',
                'Atención'
            ];
            questionario = [
                'Ingrese el número de CRNM o RNE',
                '*********',
                'Ingrese el número de CPF',
                '***.***.***-**',
                'Ingrese el número del Documento de Identificación del Mercosur',
                '************',
                'Ingrese el número del Pasaporte',
                'AA******',
                'Finalizar',
                'Cuestionario',
                'Ingrese aquí sus documentos de identificación. No se preocupe, si no tiene alguno, simplemente déjelo en blanco.',
                '¿Cuál es su condición actual?',
                'Refugiado',
                'Inmigrante'
            ];
            bar = ['Inicio', 'Noticias', 'Documentos', 'Perfil', 'Servicios'];
            perfil = [
                'Cambiar idioma',
                'Temas',
                'Notificaciones:',
                'Activadas',
                'Desactivadas',
                'Términos de uso',
                'Política de privacidad',
                'Cerrar sesión',
                'Editar perfil',
                'Automático',
                'Claro',
                'Oscuro',
                'Color',
                'Modos',
                'Colores',
                'Cambiar contraseña',
                'Registrar dirección',
                'Actualizar dirección',
                'Cargando...',
                'Error',
                'Atención',
                'Éxito',
                '✅ Éxito',
                '¡Foto de perfil actualizada!',
                '⚠️ Advertencia',
                'Foto guardada localmente, pero no se pudo sincronizar con el servidor',
                '¡Error al acceder a la galería!',
                '¡Permiso para acceder a la galería denegado!',
                'Error',
                'Usuario no identificado',
                'La imagen seleccionada no es válida',
                'Enviando código...',
                'Ingrese el código enviado',
                'Ingrese el código de 5 dígitos',
                '¡Código incorrecto!',
                'Cancelar',
                'Verificar',
                'Cambie su contraseña',
                'Ingrese su nueva contraseña',
                'Confirme su contraseña',
                'Actualizar contraseña',
                'Las contraseñas no coinciden',
                'Mi perfil',
                'Ver perfil',
                'Nombre',
                'Correo electrónico',
                'Teléfono',
                'No informado',
                'Dirección',
                'Eliminar perfil',
                'Eliminar perfil',
                '¿Está seguro de que desea eliminar su cuenta? Esta acción no se puede deshacer.',
                'Cancelar',
                'Eliminar',
                'Éxito',
                'Perfil eliminado con éxito',
                'Error',
                'No se pudo eliminar el perfil',
                'Error',
                'No se pudo cerrar sesión.',
                'Dirección',
                'Ayuda',
                'Documentos'
            ];

            cores = ['Predeterminado', 'Naranja', 'Azul', 'Morado', 'Amarillo', 'Rosa', 'Rojo', 'Verde', 'Azul Oscuro'];
            endereco = [
                'Registrar dirección',
                'Código postal',
                'Calle',
                'Número',
                'Barrio',
                'Ciudad',
                'Estado'
            ];
            enderecoAviso = [
                '⚠️ Código postal inválido. Ingrese un código válido en el formato 12345-678',
                '⚠️ Calle inválida. Ingrese una calle válida',
                '⚠️ Número inválido. Ingrese el número de la dirección',
                '⚠️ Barrio inválido. Ingrese un barrio válido',
                '⚠️ Ciudad inválida. Ingrese una ciudad válida',
                '✅ Datos actualizados con éxito!',
                '❌ Error al guardar los cambios',
                '❌ Código postal no encontrado. Verifique el código ingresado e intente de nuevo.',
                '❌ Error al buscar el código postal. Verifique su conexión.'
            ];
            home = [
                'Pase de Autobús',
                'Licencia de Conducir',
                'Pasaporte',
                'Comprobante de Domicilio',
                'Mercosur',
                'Título de Elector',
                'Hola',
                'Sistema de Salud',
                'Documentos de Identificación',
                'Números de Emergencia',
                'Lugares Importantes',
                '¡Registre su dirección para que podamos ayudarle mejor!'
            ];
            feed = [
                'Buscar noticias...',
                'resultado(s) encontrado(s) para',
                'No se encontraron noticias para',
                'Intente buscar otras palabras clave',
                'Cuadrícula',
                'Linha',
                'Leer noticia completa',
                'Noticia',
                'Cargando Noticias...'
            ];
            documentos = [
                'Números de Emergencia',
                'Documentos de Identificación',
                'Lugares Importantes',
                'Sistema de Salud',
                'Documentos de Trabajo',
                'Transporte Público',
                'Vehículos y Licencias',
                'Refugios',
                'Derechos del Inmigrante',
                'Deberes del Inmigrante'
            ];
            docs = [
                'Imagen:',
                'Descripción:',
                'Campos Principales:',
                'Validez:',
                'Uso Común:',
                'Tipos disponibles:',
                'Cerrar',
                'Requisitos:',
                'Error al cargar los documentos.',
                'No hay documentos disponibles.',
                'Local:'
            ]
            termos = [
                'Términos de Uso',
                '1. Aceptación de los Términos',
                'Al utilizar nuestros servicios, usted acepta estos términos de uso.',
                'Estos términos regulan el uso de la aplicación y todos los servicios relacionados.',
                '2. Uso del Servicio',
                'Usted acepta usar el servicio solo para fines legales y de acuerdo con estos términos.',
                'Está prohibido utilizar el servicio para actividades ilegales o no autorizadas.',
                '3. Cuenta del Usuario',
                'Usted es responsable de mantener la confidencialidad de su cuenta y contraseña.',
                'Todas las actividades realizadas en su cuenta son de su responsabilidad.',
                '4. Propiedad Intelectual',
                'Todo el contenido de la aplicación, incluidos textos, gráficos, logotipos y software,',
                'es propiedad de la empresa y está protegido por leyes de derechos de autor.',
                '5. Limitación de Responsabilidad',
                'No somos responsables de daños indirectos, incidentales o consecuentes',
                'derivados del uso o la imposibilidad de utilizar nuestros servicios.',
                '6. Modificaciones de los Términos',
                'Nos reservamos el derecho de modificar estos términos en cualquier momento.',
                'Los cambios significativos serán notificados a los usuarios.',
                '7. Ley Aplicable',
                'Estos términos se rigen por las leyes del país donde la empresa tiene su sede principal.',
                '8. Contacto',
                'Para preguntas sobre estos términos, comuníquese con el soporte de la aplicación.',
                'Entendido'
            ];
            privacidade = [
                'Política de Privacidad',
                '1. Recopilación de Información',
                'Recopilamos la información que usted nos proporciona directamente, como nombre,',
                'correo electrónico, teléfono y documentos cuando sea necesario para los servicios.',
                '2. Uso de la Información',
                'Utilizamos su información para:',
                '• Proporcionar y mejorar nuestros servicios',
                '• Personalizar su experiencia',
                '• Enviar notificaciones importantes',
                '• Cumplir con obligaciones legales',
                '3. Compartición de Datos',
                'No vendemos su información personal. Podemos compartir datos con:',
                '• Proveedores de servicios esenciales',
                '• Autoridades legales cuando lo exija la ley',
                '• Nuevos propietarios en caso de fusión o adquisición',
                '4. Seguridad de los Datos',
                'Implementamos medidas de seguridad técnicas y organizacionales para',
                'proteger su información contra el acceso o divulgación no autorizados.',
                '5. Sus Derechos',
                'Usted tiene derecho a:',
                '• Acceder a su información personal',
                '• Corregir datos inexactos',
                '• Solicitar la eliminación de sus datos',
                '• Oponerse al procesamiento de datos',
                '6. Retención de Datos',
                'Mantenemos su información solo durante el tiempo necesario para cumplir',
                'con los fines descritos en esta política o los exigidos por la ley.',
                '7. Cambios en la Política',
                'Podemos actualizar esta política periódicamente. Los cambios significativos',
                'serán notificados a través de la aplicación o por correo electrónico.',
                '8. Contacto',
                'Para ejercer sus derechos o dudas sobre privacidad,',
                'póngase en contacto con nuestro responsable de protección de datos.',
                'Entendido'
            ];



            break;

        default:
            cadastro = [
                'Cadastre-se',
                'Nome',
                'Email',
                'País de Origem',
                'Data de nascimento',
                'Crie uma senha',
                'Criar Conta',
                'Já tem conta?',
                'Clique aqui',
                'Telefone',
                'Atualizar Perfil',
                'Salvar Alterações',
                'Carregando'
            ];
            login = [
                'Bem-Vindo de volta!',
                'Digite o seu email:',
                'Digite a sua senha:',
                'Entrar',
                'Não tem uma conta?',
                'Crie uma agora'
            ];
    }

    return {
        cadastro,
        login,
        pais,
        aviso,
        questionario,
        bar,
        perfil,
        cores,
        endereco,
        enderecoAviso,
        home,
        feed,
        documentos,
        docs,
        Mapa,
        termos,
        privacidade,

    };
}

export default pegarIdioma;