import { StyleSheet, Dimensions } from 'react-native'
import { useTheme, Colors } from '../../../../themeContext';

export default function getStyles(isDarkMode) {
    const { temaCor } = useTheme();
    const { width, height } = Dimensions.get('window');

    const background = isDarkMode ? '#313131ff' : '#ffffffff'
    const cardBackground = isDarkMode ? '#1E1E1E' : '#ebebebff'
    const modalBackground = isDarkMode ? '#1E1E1E' : '#ffffffff'
    const font = isDarkMode ? '#ffffffff' : "#000000ff"
    const secondaryFont = isDarkMode ? '#cccccc' : "#666666"

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: background,
        },
        loadingContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: background,
        },
        loadingText: {
            marginTop: 20,
            fontSize: 16,
            color: font,
        },

        // Header do Perfil
        perfil: {
            width: '100%',
            height: height * 0.25,
            backgroundColor: Colors[temaCor],
            borderBottomLeftRadius: 25,
            borderBottomRightRadius: 25,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingTop: height * 0.05,
            elevation: 8,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
        },
        foto: {
            width: width * 0.25,
            height: width * 0.25,
            borderRadius: width * 0.125,
            borderWidth: 3,
            borderColor: '#ffffff',
            backgroundColor: 'rgba(255,255,255,0.2)',
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 5,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.25,
            shadowRadius: 4,
        },
        fotoImage: {
            width: '100%',
            height: '100%',
            borderRadius: width * 0.125,
        },
        placeholderContainer: {
            width: '100%',
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: width * 0.125,
            backgroundColor: Colors[temaCor],
        },
        uploadOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.5)',
            borderRadius: width * 0.125,
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 10,
        },
        errorText: {
            color: '#ff4444',
            fontSize: 12,
            textAlign: 'center',
            marginTop: 5,
        },
        info: {
            flex: 1,
            marginLeft: 20,
            justifyContent: 'center',
        },
        infoBots: {
            display: 'flex',
            flexDirection: 'row',
            gap: 10,
        },
        infoNome: {
            fontSize: 22,
            fontWeight: 'bold',
            color: '#ffffff',
            marginBottom: 5,
        },
        infoEmail: {
            fontSize: 16,
            color: 'rgba(255,255,255,0.8)',
            marginBottom: 15,
        },
        infoBtn: {
            backgroundColor: 'rgba(255,255,255,0.2)',
            paddingHorizontal: 20,
            paddingVertical: 8,
            borderRadius: 20,
            alignSelf: 'flex-start',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.3)',
        },
        infoBtnText: {
            fontSize: 14,
            fontWeight: '600',
            color: '#ffffff',
        },

        // Grid de Botões
        botoes: {
            flex: 1,
            paddingVertical: 20,
        },
        lista: {
            flex: 1,
        },
        botao: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 15,
            paddingHorizontal: 25,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#444' : '#e0e0e0',
            backgroundColor: background,
        },
        botaoTexto: {
            fontSize: 18,
            color: font,
            marginLeft: 20,
            fontWeight: '500',
        },

        // Modal de Tema
        modalTemaContainer: {
            flex: 1,
            backgroundColor: background,
            paddingTop: height * 0.05,
        },
        modalTemaTitulo: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 15,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalTitulo: {
            fontSize: 28,
            fontWeight: 'bold',
            color: font,
            flex: 1,
            textAlign: 'center',
            marginRight: 50,
        },
        textTituloModal: {
            fontSize: 20,
            fontWeight: '600',
            color: font,
            textAlign: 'center',
            marginVertical: 20,
        },
        modalLinha: {
            flexDirection: 'row',
            justifyContent: 'space-around',
            paddingHorizontal: 20,
            paddingVertical: 20,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#444' : '#e0e0e0',
        },
        modalTemaView: {
            alignItems: 'center',
            padding: 10,
            borderRadius: 15,
            borderWidth: 2,
            borderColor: 'transparent',
        },
        modalTema: {
            width: 80,
            height: 80,
            borderRadius: 40,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 10,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        modalTemaText: {
            fontSize: 14,
            color: font,
            textAlign: 'center',
            fontWeight: '500',
        },
        select: {
            borderColor: Colors[temaCor],
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f0f0f0',
            transform: [{ scale: 1.05 }],
        },
        flat: {
            flex: 1,
            paddingVertical: 10,
        },
        flatContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 15,
            paddingHorizontal: 25,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#444' : '#e0e0e0',
        },
        flatCor: {
            width: 40,
            height: 40,
            borderRadius: 8,
            marginRight: 15,
        },
        flatText: {
            fontSize: 18,
            color: font,
            fontWeight: '500',
        },

        // Modais de Verificação
        modalContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'rgba(0, 0, 0, 0.7)',
        },

        // Modal de Carregamento
        modalLoadingContent: {
            backgroundColor: modalBackground,
            borderRadius: 20,
            width: width * 0.8,
            height: height * 0.25,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            overflow: 'hidden',
        },
        modalLoadingHeader: {
            width: '100%',
            height: 60,
            backgroundColor: cardBackground,
            justifyContent: 'center',
            alignItems: 'center',
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalLoadingTitulo: {
            fontSize: 20,
            fontWeight: 'bold',
            color: font,
        },
        modalLoadingBody: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 25,
        },
        modalLoadingText: {
            fontSize: 16,
            color: font,
            textAlign: 'center',
            lineHeight: 22,
            marginTop: 15,
        },

        // Modal do Código
        modalCodigoContent: {
            backgroundColor: modalBackground,
            borderRadius: 20,
            width: width * 0.85,
            height: height * 0.45,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            overflow: 'hidden',
        },
        modalCodigoHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            height: 60,
            backgroundColor: cardBackground,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalCodigoTitulo: {
            fontSize: 22,
            fontWeight: 'bold',
            color: font,
            flex: 1,
            textAlign: 'center',
        },
        modalHeaderSpacer: {
            width: 30,
        },
        modalCodigoBody: {
            flex: 1,
            padding: 25,
            justifyContent: 'center',
            alignItems: 'center',
        },
        codigoIconContainer: {
            marginBottom: 15,
        },
        codigoInstructionText: {
            fontSize: 16,
            color: font,
            textAlign: 'center',
            lineHeight: 22,
            marginBottom: 20,
        },
        codigoInput: {
            width: '70%',
            height: 60,
            borderWidth: 2,
            borderColor: Colors[temaCor],
            borderRadius: 15,
            fontSize: 24,
            fontWeight: 'bold',
            color: font,
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f8f8',
            textAlign: 'center',
            letterSpacing: 10,
            marginBottom: 10,
        },
        codigoErrorText: {
            color: '#ff4444',
            fontSize: 14,
            textAlign: 'center',
            marginBottom: 10,
        },
        codigoButtonContainer: {
            flexDirection: 'row',
            width: '100%',
            gap: 10,
            marginTop: 10,
        },
        codigoCancelButton: {
            flex: 1,
            height: 50,
            borderWidth: 2,
            borderColor: isDarkMode ? '#444' : '#e0e0e0',
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f8f8',
        },
        codigoCancelButtonText: {
            fontSize: 16,
            fontWeight: '600',
            color: font,
        },
        codigoVerifyButton: {
            flex: 1,
            height: 50,
            borderRadius: 12,
            overflow: 'hidden',
        },
        codigoButtonGradient: {
            backgroundColor: Colors[temaCor],
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
        },
        codigoButtonDisabled: {
            opacity: 0.6,
        },
        codigoVerifyButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },

        // Modal da Senha
        modalSenhaContent: {
            backgroundColor: modalBackground,
            borderRadius: 20,
            width: width * 0.85,
            height: height * 0.45,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            overflow: 'hidden',
        },
        modalSenhaHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            height: 60,
            backgroundColor: cardBackground,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalCloseButton: {
            padding: 5,
        },
        modalSenhaTitulo: {
            fontSize: 22,
            fontWeight: 'bold',
            color: font,
            flex: 1,
            textAlign: 'center',
        },
        modalSenhaBody: {
            flex: 1,
            padding: 25,
            justifyContent: 'center',
        },
        senhaInputContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: isDarkMode ? '#444' : '#e0e0e0',
            borderRadius: 12,
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f8f8',
            paddingHorizontal: 15,
            height: 50,
            marginBottom: 15,
        },
        inputIcon: {
            marginRight: 10,
        },
        senhaInput: {
            flex: 1,
            fontSize: 16,
            color: font,
        },
        senhaErrorText: {
            color: '#ff4444',
            fontSize: 14,
            textAlign: 'center',
            marginBottom: 10,
        },
        senhaConfirmButton: {
            height: 50,
            borderRadius: 12,
            overflow: 'hidden',
            marginTop: 10,
        },
        senhaButtonGradient: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
        },
        senhaButtonDisabled: {
            opacity: 0.6,
        },
        senhaButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },

        // Modal do Perfil
        modalPerfilOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
            justifyContent: 'flex-end',
        },
        modalPerfilContainer: {
            height: '90%',
            backgroundColor: modalBackground,
            borderTopLeftRadius: 25,
            borderTopRightRadius: 25,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: -4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            overflow: 'hidden',
        },
        modalPerfilHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 15,
            backgroundColor: cardBackground,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalPerfilTitle: {
            fontSize: 24,
            fontWeight: 'bold',
            color: font,
        },
        modalPerfilCloseButton: {
            padding: 5,
        },
        modalPerfilContent: {
            flex: 1,
        },
        modalFotoContainer: {
            alignItems: 'center',
            paddingVertical: 30,
            backgroundColor: Colors[temaCor] + '20',
        },
        modalFoto: {
            width: 120,
            height: 120,
            borderRadius: 60,
            borderWidth: 3,
            borderColor: Colors[temaCor],
        },
        modalFotoEditButton: {
            position: 'absolute',
            bottom: 25,
            right: width * 0.35,
            backgroundColor: Colors[temaCor],
            width: 40,
            height: 40,
            borderRadius: 20,
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 5,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.25,
            shadowRadius: 4,
        },
        modalInfoContainer: {
            padding: 20,
        },
        modalInfoItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 15,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#444' : '#e0e0e0',
        },
        modalInfoText: {
            flex: 1,
            marginLeft: 15,
        },
        modalInfoLabel: {
            fontSize: 14,
            color: secondaryFont,
            marginBottom: 4,
        },
        modalInfoValue: {
            fontSize: 16,
            color: font,
            fontWeight: '500',
        },
        modalActionsContainer: {
            flexDirection: 'row',
            padding: 20,
            gap: 10,
            borderTopWidth: 1,
            borderTopColor: isDarkMode ? '#444' : '#e0e0e0',
            backgroundColor: cardBackground,
        },
        modalEditButton: {
            flex: 1,
            flexDirection: 'row',
            backgroundColor: Colors[temaCor],
            paddingVertical: 12,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
        },
        modalEditButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },
        modalDeleteButton: {
            flex: 1,
            flexDirection: 'row',
            backgroundColor: '#ff4444',
            paddingVertical: 12,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
        },
        modalDeleteButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },
        placeholderContainer: {
            width: 120,
            height: 120,
            borderRadius: 60,
            backgroundColor: Colors[temaCor],
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: '#fff',
        },
        placeholderText: {
            color: '#ffffffff',
            fontSize: 50,
            fontWeight: 'bold',
        },
        modalDocumentosOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        modalDocumentosContainer: {
            backgroundColor: modalBackground,
            borderRadius: 20,
            width: width * 0.9,
            height: height * 0.8,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            overflow: 'hidden',
        },
        modalDocumentosHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 15,
            backgroundColor: cardBackground,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalDocumentosTitle: {
            fontSize: 22,
            fontWeight: 'bold',
            color: font,
            flex: 1,
            textAlign: 'center',
        },
        modalDocumentosCloseButton: {
            padding: 5,
        },
        modalDocumentosContent: {
            flex: 1,
            padding: 20,
        },
        modalDocumentosText: {
            fontSize: 14,
            color: font,
            lineHeight: 20,
            textAlign: 'justify',
        },
        modalDocumentosSectionTitle: {
            fontSize: 16,
            fontWeight: 'bold',
            color: Colors[temaCor],
            marginTop: 10,
        },
        modalDocumentosActions: {
            padding: 20,
            borderTopWidth: 1,
            borderTopColor: isDarkMode ? '#444' : '#e0e0e0',
            backgroundColor: cardBackground,
        },
        modalDocumentosButton: {
            backgroundColor: Colors[temaCor],
            paddingVertical: 12,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modalDocumentosButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },
        modalDocumentosContainer: {
            flex: 1,
            backgroundColor: background,
        },
        modalDocumentosHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 15,
            backgroundColor: cardBackground,
            borderBottomWidth: 2,
            borderBottomColor: Colors[temaCor],
        },
        modalDocumentosBackButton: {
            padding: 5,
        },
        modalDocumentosTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: font,
            flex: 1,
            textAlign: 'center',
        },
        modalHeaderSpacer: {
            width: 30,
        },
        modalDocumentosContent: {
            flex: 1,
            padding: 20,
        },
        documentosSection: {
            marginBottom: 20,
        },
        documentosSectionTitle: {
            fontSize: 18,
            fontWeight: 'bold',
            color: font,
            marginBottom: 15,
        },
        documentosVazio: {
            alignItems: 'center',
            paddingVertical: 40,
            backgroundColor: cardBackground,
            borderRadius: 12,
            padding: 20,
        },
        documentosVazioText: {
            fontSize: 16,
            fontWeight: '600',
            color: font,
            marginTop: 15,
            marginBottom: 8,
            textAlign: 'center',
        },
        documentosVazioSubtext: {
            fontSize: 14,
            color: secondaryFont,
            textAlign: 'center',
            lineHeight: 20,
        },
        documentoCard: {
            backgroundColor: cardBackground,
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            borderLeftWidth: 4,
            borderLeftColor: Colors[temaCor],
        },
        documentoHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 12,
        },
        documentoIconContainer: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: Colors[temaCor] + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        documentoInfo: {
            flex: 1,
        },
        documentoName: {
            fontSize: 16,
            fontWeight: 'bold',
            color: font,
            marginBottom: 4,
        },
        documentoNumber: {
            fontSize: 14,
            color: secondaryFont,
        },
        statusBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 10,
            paddingVertical: 6,
            borderRadius: 12,
            gap: 4,
        },
        statusVerified: {
            backgroundColor: '#4CAF50',
        },
        statusText: {
            fontSize: 12,
            fontWeight: '600',
            color: '#fff',
        },
        documentoActions: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            gap: 10,
        },
        documentoActionButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderWidth: 1,
            borderColor: Colors[temaCor],
            borderRadius: 8,
            gap: 6,
        },
        documentoActionText: {
            fontSize: 14,
            fontWeight: '600',
        },
        adicionarDocumentoButton: {
            flexDirection: 'row',
            backgroundColor: Colors[temaCor],
            paddingVertical: 15,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            gap: 8,
            marginTop: 10,
        },
        adicionarDocumentoText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
        },
    });
}