import { StyleSheet, Dimensions } from 'react-native'
import { useTheme, Colors } from '../../../../../../themeContext';

export default function getStyles(isDarkMode) {
    const { temaCor } = useTheme();
    const { width, height } = Dimensions.get('window');

    const background = isDarkMode ? '#313131ff' : '#ffffffff'
    const cardBackground = isDarkMode ? '#1E1E1E' : '#ebebebff'
    const modalBackground = isDarkMode ? '#1a1a1a' : '#fff'
    const font = isDarkMode ? '#ffffffff' : "#000000ff"
    const secondaryFont = isDarkMode ? '#cccccc' : "#666666"

    return StyleSheet.create({
        container: {
            width: width,
            height: height + height * 0.048,
            backgroundColor: background,
        },
        header: {
            width: width,
            height: height * 0.12,
            backgroundColor: isDarkMode ? '#2A2A2A' : '#F8F8F8',
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: width * 0.04,
            borderBottomWidth: 1,
            borderBottomColor: isDarkMode ? '#444' : '#E0E0E0',
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 3,
        },
        backButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: 8,
            backgroundColor: isDarkMode ? '#3A3A3A' : '#F0F0F0',
        },
        backButtonText: {
            fontSize: width * 0.04,
            color: Colors[temaCor],
            fontWeight: '600',
            marginLeft: 8,
        },
        content: {
            paddingTop: 20,
            flex: 1,
        },
        card: {
            backgroundColor: cardBackground,
            alignSelf: 'center',
            width: width * 0.95,
            padding: 20,
            borderRadius: 16,
            marginBottom: 12,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            borderLeftWidth: 4,
            borderLeftColor: Colors[temaCor],
        },
        line: {
            height: 2,
            backgroundColor: isDarkMode ? '#444' : '#E0E0E0',
            marginVertical: 5,
            display: 'flex',
            width: '100%',
        },
        title: {
            fontSize: 18,
            fontWeight: 'bold',
            color: font,
            marginBottom: 6,
        },
        categoryTitle:{
            fontSize: 22    ,
            fontWeight: 'bold',
            color: font,
            marginBottom: 6,
            marginTop: 6,
            textAlign: 'center',
        },
        subtitle: {
            fontSize: 14,
            color: secondaryFont,
            lineHeight: 20,
        },
        noDataText: {
            fontSize: 16,
            color: secondaryFont,
            textAlign: 'center',
            marginTop: 50,
            fontStyle: 'italic',
        },

        // MODAL STYLES
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 20,
        },
        modalContainer: {
            width: '100%',
            maxHeight: '95%',
            backgroundColor: modalBackground,
            borderRadius: 20,
            padding: 24,
            elevation: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
        },
        modalTitle: {
            fontSize: 24,
            fontWeight: 'bold',
            color: font,
            marginBottom: 20,
            textAlign: 'center',
            lineHeight: 32,
        },
        sectionTitle: {
            fontSize: 18,
            fontWeight: '600',
            color: Colors[temaCor],
            marginTop: 20,
            marginBottom: 8,
            lineHeight: 24,
        },
        text: {
            fontSize: 16,
            color: font,
            lineHeight: 24,
            textAlign: 'justify',
        },
        image: {
            width: '100%',
            height: 200,
            marginTop: 12,
            marginBottom: 8,
            borderRadius: 12,
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f0f0f0',
        },
        tipoButton: {
            backgroundColor: Colors[temaCor] + '20',
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: 12,
            marginVertical: 6,
            borderWidth: 1,
            borderColor: Colors[temaCor] + '40',
        },
        tipoButtonText: {
            fontSize: 16,
            fontWeight: '600',
            color: Colors[temaCor],
            textAlign: 'center',
        },
        closeButton: {
            backgroundColor: Colors[temaCor],
            paddingVertical: 14,
            borderRadius: 12,
            marginTop: 20,
            elevation: 3,
            shadowColor: Colors[temaCor],
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 4,
        },
        closeButtonText: {
            color: '#fff',
            textAlign: 'center',
            fontWeight: '600',
            fontSize: 16,
            letterSpacing: 0.5,
        },

        // Loading states (caso precise no futuro)
        loadingContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: background,
        },
        loadingText: {
            marginTop: 20,
            fontSize: 16,
            color: font,
        },
        requisitosContainer: {
            marginTop: 8,
            marginBottom: 8,
        },
        requisitoItem: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDarkMode ? '#2a2a2a' : '#f8f8f8',
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: 12,
            marginBottom: 8,
            borderWidth: 1,
            borderColor: isDarkMode ? '#444' : '#e8e8e8',
        },
        requisitoIcon: {
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: Colors[temaCor] + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        requisitoText: {
            flex: 1,
            fontSize: 14,
            color: font,
            lineHeight: 20,
        },
        mapContainer: {
            width: '100%',
            height: height * 0.15,
            marginTop: 12,
            borderRadius: 16,
            overflow: 'hidden',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#ffffff',
            borderWidth: 2,
            borderColor: Colors[temaCor],
            borderStyle: 'dashed',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.1,
            shadowRadius: 3.84,
            elevation: 3,
        },
        // Adicione estilos para:
        textContainer: {
            backgroundColor: '#f5f5f5',
            padding: 10,
            borderRadius: 8,
            marginBottom: 15,
        },
        resultText: {
            fontSize: 14,
            lineHeight: 20,
            color: '#333',
        },
        buttonRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginTop: 20,
            gap: 10,
        },
        primaryButton: {
            backgroundColor: Colors.primary,
            padding: 15,
            borderRadius: 8,
            flex: 1,
            alignItems: 'center',
        },
        secondaryButton: {
            backgroundColor: '#ccc',
            padding: 15,
            borderRadius: 8,
            flex: 1,
            alignItems: 'center',
        },
        primaryButtonText: {
            color: 'white',
            fontWeight: 'bold',
        },
        secondaryButtonText: {
            color: '#333',
            fontWeight: 'bold',
        },
        scannedInfo: {
            backgroundColor: '#f0f8ff',
            padding: 15,
            margin: 10,
            borderRadius: 8,
            borderLeftWidth: 4,
            borderLeftColor: '#007AFF',
        },
        scannedTitle: {
            fontSize: 16,
            fontWeight: 'bold',
            color: '#333',
            marginBottom: 5,
        },
        scannedText: {
            fontSize: 14,
            color: '#666',
            fontStyle: 'italic',
        },
    });
}