
import React from 'react';
import { Image } from 'react-native';
import { useIdioma } from '../../../../idiomaContext';

export const usePaisesComBandeiras = () => {
  const { textos } = useIdioma();
  const pais = textos?.pais || [];

  const paisesComBandeiras = [
    { label: pais[0], value: 'Afeganistão', icon: () => <Image source={require('../../../../assets/bandeiras/af.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[1], value: 'África do Sul', icon: () => <Image source={require('../../../../assets/bandeiras/za.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[2], value: 'Albânia', icon: () => <Image source={require('../../../../assets/bandeiras/al.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[3], value: 'Alemanha', icon: () => <Image source={require('../../../../assets/bandeiras/de.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[4], value: 'Andorra', icon: () => <Image source={require('../../../../assets/bandeiras/ad.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[5], value: 'Angola', icon: () => <Image source={require('../../../../assets/bandeiras/ao.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[6], value: 'Anguilla', icon: () => <Image source={require('../../../../assets/bandeiras/ai.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[7], value: 'Antártida', icon: () => <Image source={require('../../../../assets/bandeiras/aq.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[8], value: 'Antígua e Barbuda', icon: () => <Image source={require('../../../../assets/bandeiras/ag.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[9], value: 'Arábia Saudita', icon: () => <Image source={require('../../../../assets/bandeiras/sa.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[10], value: 'Argélia', icon: () => <Image source={require('../../../../assets/bandeiras/dz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[11], value: 'Argentina', icon: () => <Image source={require('../../../../assets/bandeiras/ar.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[12], value: 'Armênia', icon: () =><Image source={require('../../../../assets/bandeiras/am.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[13], value: 'Aruba', icon: () => <Image source={require('../../../../assets/bandeiras/aw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[14], value: 'Austrália', icon: () => <Image source={require('../../../../assets/bandeiras/au.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[15], value: 'Áustria', icon: () => <Image source={require('../../../../assets/bandeiras/at.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[16], value: 'Azerbaijão', icon: () => <Image source={require('../../../../assets/bandeiras/az.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[17], value: 'Bahamas', icon: () => <Image source={require('../../../../assets/bandeiras/bs.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[18], value: 'Bahrein', icon: () => <Image source={require('../../../../assets/bandeiras/bh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[19], value: 'Bangladesh', icon: () => <Image source={require('../../../../assets/bandeiras/bd.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[20], value: 'Barbados', icon: () => <Image source={require('../../../../assets/bandeiras/bb.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[21], value: 'Bélgica', icon: () => <Image source={require('../../../../assets/bandeiras/be.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[22], value: 'Belize', icon: () => <Image source={require('../../../../assets/bandeiras/bz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[23], value: 'Benin', icon: () => <Image source={require('../../../../assets/bandeiras/bj.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[24], value: 'Bermudas', icon: () => <Image source={require('../../../../assets/bandeiras/bm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[25], value: 'Bielorrússia', icon: () => <Image source={require('../../../../assets/bandeiras/by.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[26], value: 'Bolívia', icon: () => <Image source={require('../../../../assets/bandeiras/bo.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[27], value: 'Bonaire', icon: () => <Image source={require('../../../../assets/bandeiras/bq.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[28], value: 'Bósnia e Herzegovina', icon: () => <Image source={require('../../../../assets/bandeiras/ba.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[29], value: 'Botsuana', icon: () => <Image source={require('../../../../assets/bandeiras/bw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[30], value: 'Brasil', icon: () => <Image source={require('../../../../assets/bandeiras/br.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[31], value: 'Brunei', icon: () => <Image source={require('../../../../assets/bandeiras/bn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[32], value: 'Bulgária', icon: () => <Image source={require('../../../../assets/bandeiras/bg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[33], value: 'Burkina Faso', icon: () => <Image source={require('../../../../assets/bandeiras/bf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[34], value: 'Burundi', icon: () => <Image source={require('../../../../assets/bandeiras/bi.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[35], value: 'Butão', icon: () => <Image source={require('../../../../assets/bandeiras/bt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[36], value: 'Cabo Verde', icon: () => <Image source={require('../../../../assets/bandeiras/cv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[37], value: 'Camboja', icon: () => <Image source={require('../../../../assets/bandeiras/kh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[38], value: 'Camarões', icon: () => <Image source={require('../../../../assets/bandeiras/cm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[39], value: 'Canadá', icon: () => <Image source={require('../../../../assets/bandeiras/ca.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[40], value: 'Catar', icon: () => <Image source={require('../../../../assets/bandeiras/qa.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[41], value: 'Cazaquistão', icon: () => <Image source={require('../../../../assets/bandeiras/kz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[42], value: 'Chade', icon: () => <Image source={require('../../../../assets/bandeiras/td.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[43], value: 'Chile', icon: () => <Image source={require('../../../../assets/bandeiras/cl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[44], value: 'China', icon: () => <Image source={require('../../../../assets/bandeiras/cn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[45], value: 'Chipre', icon: () => <Image source={require('../../../../assets/bandeiras/cy.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[46], value: 'Colômbia', icon: () => <Image source={require('../../../../assets/bandeiras/co.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[47], value: 'Comores', icon: () => <Image source={require('../../../../assets/bandeiras/km.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[48], value: 'Congo', icon: () => <Image source={require('../../../../assets/bandeiras/cg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[49], value: 'Congo (República Democrática)', icon: () => <Image source={require('../../../../assets/bandeiras/cd.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[50], value: 'Coreia do Sul', icon: () => <Image source={require('../../../../assets/bandeiras/kr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[51], value: 'Coreia do Norte', icon: () => <Image source={require('../../../../assets/bandeiras/kp.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[52], value: 'Costa do Marfim', icon: () => <Image source={require('../../../../assets/bandeiras/ci.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[53], value: 'Costa Rica', icon: () => <Image source={require('../../../../assets/bandeiras/cr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[54], value: 'Croácia', icon: () => <Image source={require('../../../../assets/bandeiras/hr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[55], value: 'Cuba', icon: () => <Image source={require('../../../../assets/bandeiras/cu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[56], value: 'Curaçao', icon: () => <Image source={require('../../../../assets/bandeiras/cw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[57], value: 'Djibuti', icon: () => <Image source={require('../../../../assets/bandeiras/dj.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[58], value: 'Dominica', icon: () => <Image source={require('../../../../assets/bandeiras/dm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[59], value: 'Egito', icon: () => <Image source={require('../../../../assets/bandeiras/eg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[60], value: 'El Salvador', icon: () => <Image source={require('../../../../assets/bandeiras/sv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[61], value: 'Emirados Árabes Unidos', icon: () => <Image source={require('../../../../assets/bandeiras/ae.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[62], value: 'Equador', icon: () => <Image source={require('../../../../assets/bandeiras/ec.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[63], value: 'Eritreia', icon: () => <Image source={require('../../../../assets/bandeiras/er.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[64], value: 'Eslováquia', icon: () => <Image source={require('../../../../assets/bandeiras/sk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[65], value: 'Eslovênia', icon: () => <Image source={require('../../../../assets/bandeiras/si.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[66], value: 'Espanha', icon: () => <Image source={require('../../../../assets/bandeiras/es.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[67], value: 'Essuatíni', icon: () => <Image source={require('../../../../assets/bandeiras/sz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[68], value: 'Estados Unidos', icon: () => <Image source={require('../../../../assets/bandeiras/us.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[69], value: 'Estônia', icon: () => <Image source={require('../../../../assets/bandeiras/ee.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[70], value: 'Etiópia', icon: () => <Image source={require('../../../../assets/bandeiras/et.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[71], value: 'Rússia', icon: () => <Image source={require('../../../../assets/bandeiras/ru.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[72], value: 'Fiji', icon: () => <Image source={require('../../../../assets/bandeiras/fj.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[73], value: 'Filipinas', icon: () => <Image source={require('../../../../assets/bandeiras/ph.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[74], value: 'Finlândia', icon: () => <Image source={require('../../../../assets/bandeiras/fi.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[75], value: 'França', icon: () => <Image source={require('../../../../assets/bandeiras/fr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[76], value: 'Gabão', icon: () => <Image source={require('../../../../assets/bandeiras/ga.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[77], value: 'Gâmbia', icon: () => <Image source={require('../../../../assets/bandeiras/gm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[78], value: 'Gana', icon: () => <Image source={require('../../../../assets/bandeiras/gh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[79], value: 'Geórgia', icon: () => <Image source={require('../../../../assets/bandeiras/ge.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[80], value: 'Geórgia do Sul e Sandwich do Sul', icon: () => <Image source={require('../../../../assets/bandeiras/gs.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[81], value: 'Gibraltar', icon: () => <Image source={require('../../../../assets/bandeiras/gi.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[82], value: 'Granada', icon: () => <Image source={require('../../../../assets/bandeiras/gd.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[83], value: 'Groenlândia', icon: () => <Image source={require('../../../../assets/bandeiras/gl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[84], value: 'Guadalupe', icon: () => <Image source={require('../../../../assets/bandeiras/gp.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[85], value: 'Guam', icon: () => <Image source={require('../../../../assets/bandeiras/gu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[86], value: 'Guatemala', icon: () => <Image source={require('../../../../assets/bandeiras/gt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[87], value: 'Guernsey', icon: () => <Image source={require('../../../../assets/bandeiras/gg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[88], value: 'Guiana', icon: () => <Image source={require('../../../../assets/bandeiras/gy.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[89], value: 'Guiana Francesa', icon: () => <Image source={require('../../../../assets/bandeiras/gf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[90], value: 'Guiné', icon: () => <Image source={require('../../../../assets/bandeiras/gn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[91], value: 'Guiné Equatorial', icon: () => <Image source={require('../../../../assets/bandeiras/gq.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[92], value: 'Guiné-Bissau', icon: () => <Image source={require('../../../../assets/bandeiras/gw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[93], value: 'Haiti', icon: () => <Image source={require('../../../../assets/bandeiras/ht.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[94], value: 'Honduras', icon: () => <Image source={require('../../../../assets/bandeiras/hn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[95], value: 'Hong Kong', icon: () => <Image source={require('../../../../assets/bandeiras/hk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[96], value: 'Hungria', icon: () => <Image source={require('../../../../assets/bandeiras/hu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[97], value: 'Iêmen', icon: () => <Image source={require('../../../../assets/bandeiras/ye.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[98], value: 'Ilha Bouvet', icon: () => <Image source={require('../../../../assets/bandeiras/bv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[99], value: 'Ilha Christmas', icon: () => <Image source={require('../../../../assets/bandeiras/cx.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[100], value: 'Ilha de Man', icon: () => <Image source={require('../../../../assets/bandeiras/im.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[101], value: 'Ilha Heard e McDonald', icon: () => <Image source={require('../../../../assets/bandeiras/hm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[102], value: 'Ilha Norfolk', icon: () => <Image source={require('../../../../assets/bandeiras/nf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[103], value: 'Ilhas Åland', icon: () => <Image source={require('../../../../assets/bandeiras/ax.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[104], value: 'Ilhas Cayman', icon: () => <Image source={require('../../../../assets/bandeiras/ky.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[105], value: 'Ilhas Cocos (Keeling)', icon: () => <Image source={require('../../../../assets/bandeiras/cc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[106], value: 'Ilhas Cook', icon: () => <Image source={require('../../../../assets/bandeiras/ck.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[107], value: 'Ilhas Falkland (Malvinas)', icon: () => <Image source={require('../../../../assets/bandeiras/fk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[108], value: 'Ilhas Marianas do Norte', icon: () => <Image source={require('../../../../assets/bandeiras/mp.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[109], value: 'Ilhas Marshall', icon: () => <Image source={require('../../../../assets/bandeiras/mh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[110], value: 'Ilhas Menores Distantes dos EUA', icon: () => <Image source={require('../../../../assets/bandeiras/um.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[111], value: 'Ilhas Salomão', icon: () => <Image source={require('../../../../assets/bandeiras/sb.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[112], value: 'Ilhas Turcas e Caicos', icon: () => <Image source={require('../../../../assets/bandeiras/tc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[113], value: 'Ilhas Virgens Americanas', icon: () => <Image source={require('../../../../assets/bandeiras/vi.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[114], value: 'Ilhas Virgens Britânicas', icon: () => <Image source={require('../../../../assets/bandeiras/vg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[115], value: 'Índia', icon: () => <Image source={require('../../../../assets/bandeiras/in.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[116], value: 'Indonésia', icon: () => <Image source={require('../../../../assets/bandeiras/id.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[117], value: 'Iraque', icon: () => <Image source={require('../../../../assets/bandeiras/iq.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[118], value: 'Irã', icon: () => <Image source={require('../../../../assets/bandeiras/ir.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[119], value: 'Irlanda', icon: () => <Image source={require('../../../../assets/bandeiras/ie.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[120], value: 'Islândia', icon: () => <Image source={require('../../../../assets/bandeiras/is.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[121], value: 'Israel', icon: () => <Image source={require('../../../../assets/bandeiras/il.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[122], value: 'Itália', icon: () => <Image source={require('../../../../assets/bandeiras/it.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[123], value: 'Jamaica', icon: () => <Image source={require('../../../../assets/bandeiras/jm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[124], value: 'Japão', icon: () => <Image source={require('../../../../assets/bandeiras/jp.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[125], value: 'Jersey', icon: () => <Image source={require('../../../../assets/bandeiras/je.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[126], value: 'Jordânia', icon: () => <Image source={require('../../../../assets/bandeiras/jo.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[127], value: 'Kiribati', icon: () => <Image source={require('../../../../assets/bandeiras/ki.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[128], value: 'Kosovo', icon: () => <Image source={require('../../../../assets/bandeiras/xk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[129], value: 'Kuwait', icon: () => <Image source={require('../../../../assets/bandeiras/kw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[130], value: 'Laos', icon: () => <Image source={require('../../../../assets/bandeiras/la.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[131], value: 'Lesoto', icon: () => <Image source={require('../../../../assets/bandeiras/ls.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[132], value: 'Letônia', icon: () => <Image source={require('../../../../assets/bandeiras/lv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[133], value: 'Líbano', icon: () => <Image source={require('../../../../assets/bandeiras/lb.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[134], value: 'Libéria', icon: () => <Image source={require('../../../../assets/bandeiras/lr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[135], value: 'Líbia', icon: () => <Image source={require('../../../../assets/bandeiras/ly.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[136], value: 'Liechtenstein', icon: () => <Image source={require('../../../../assets/bandeiras/li.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[137], value: 'Lituânia', icon: () => <Image source={require('../../../../assets/bandeiras/lt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[138], value: 'Luxemburgo', icon: () => <Image source={require('../../../../assets/bandeiras/lu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[139], value: 'Macau', icon: () => <Image source={require('../../../../assets/bandeiras/mo.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[140], value: 'Macedônia do Norte', icon: () => <Image source={require('../../../../assets/bandeiras/mk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[141], value: 'Madagascar', icon: () => <Image source={require('../../../../assets/bandeiras/mg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[142], value: 'Malawi', icon: () => <Image source={require('../../../../assets/bandeiras/mw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[143], value: 'Malásia', icon: () => <Image source={require('../../../../assets/bandeiras/my.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[144], value: 'Maldivas', icon: () => <Image source={require('../../../../assets/bandeiras/mv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[145], value: 'Mali', icon: () => <Image source={require('../../../../assets/bandeiras/ml.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[146], value: 'Malta', icon: () => <Image source={require('../../../../assets/bandeiras/mt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[147], value: 'Marrocos', icon: () => <Image source={require('../../../../assets/bandeiras/ma.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[148], value: 'Martinica', icon: () => <Image source={require('../../../../assets/bandeiras/mq.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[149], value: 'Maurício', icon: () => <Image source={require('../../../../assets/bandeiras/mu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[150], value: 'Mauritânia', icon: () => <Image source={require('../../../../assets/bandeiras/mr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[151], value: 'Mayotte', icon: () => <Image source={require('../../../../assets/bandeiras/yt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[152], value: 'México', icon: () => <Image source={require('../../../../assets/bandeiras/mx.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[153], value: 'Micronésia', icon: () => <Image source={require('../../../../assets/bandeiras/fm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[154], value: 'Mianmar', icon: () => <Image source={require('../../../../assets/bandeiras/mm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[155], value: 'Moldávia', icon: () => <Image source={require('../../../../assets/bandeiras/md.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[156], value: 'Mônaco', icon: () => <Image source={require('../../../../assets/bandeiras/mc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[157], value: 'Mongólia', icon: () => <Image source={require('../../../../assets/bandeiras/mn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[158], value: 'Montenegro', icon: () => <Image source={require('../../../../assets/bandeiras/me.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[159], value: 'Montserrat', icon: () => <Image source={require('../../../../assets/bandeiras/ms.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[160], value: 'Moçambique', icon: () => <Image source={require('../../../../assets/bandeiras/mz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[161], value: 'Namíbia', icon: () => <Image source={require('../../../../assets/bandeiras/na.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[162], value: 'Nauru', icon: () => <Image source={require('../../../../assets/bandeiras/nr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[163], value: 'Nepal', icon: () => <Image source={require('../../../../assets/bandeiras/np.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[164], value: 'Nicarágua', icon: () => <Image source={require('../../../../assets/bandeiras/ni.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[165], value: 'Níger', icon: () => <Image source={require('../../../../assets/bandeiras/ne.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[166], value: 'Nigéria', icon: () => <Image source={require('../../../../assets/bandeiras/ng.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[167], value: 'Niue', icon: () => <Image source={require('../../../../assets/bandeiras/nu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[168], value: 'Noruega', icon: () => <Image source={require('../../../../assets/bandeiras/no.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[169], value: 'Nova Caledônia', icon: () => <Image source={require('../../../../assets/bandeiras/nc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[170], value: 'Nova Zelândia', icon: () => <Image source={require('../../../../assets/bandeiras/nz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[171], value: 'Omã', icon: () => <Image source={require('../../../../assets/bandeiras/om.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[172], value: 'Países Baixos', icon: () => <Image source={require('../../../../assets/bandeiras/nl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[173], value: 'Paquistão', icon: () => <Image source={require('../../../../assets/bandeiras/pk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[174], value: 'Palau', icon: () => <Image source={require('../../../../assets/bandeiras/pw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[175], value: 'Palestina', icon: () => <Image source={require('../../../../assets/bandeiras/ps.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[176], value: 'Panamá', icon: () => <Image source={require('../../../../assets/bandeiras/pa.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[177], value: 'Papua-Nova Guiné', icon: () => <Image source={require('../../../../assets/bandeiras/pg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[178], value: 'Paraguai', icon: () => <Image source={require('../../../../assets/bandeiras/py.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[179], value: 'Peru', icon: () => <Image source={require('../../../../assets/bandeiras/pe.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[180], value: 'Ilhas Pitcairn', icon: () => <Image source={require('../../../../assets/bandeiras/pn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[181], value: 'Polinésia Francesa', icon: () => <Image source={require('../../../../assets/bandeiras/pf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[182], value: 'Polônia', icon: () => <Image source={require('../../../../assets/bandeiras/pl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[183], value: 'Porto Rico', icon: () => <Image source={require('../../../../assets/bandeiras/pr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[184], value: 'Portugal', icon: () => <Image source={require('../../../../assets/bandeiras/pt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[185], value: 'Quênia', icon: () => <Image source={require('../../../../assets/bandeiras/ke.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[186], value: 'Quirguistão', icon: () => <Image source={require('../../../../assets/bandeiras/kg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[187], value: 'Reino Unido', icon: () => <Image source={require('../../../../assets/bandeiras/gb.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[188], value: 'Síria', icon: () => <Image source={require('../../../../assets/bandeiras/sy.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[189], value: 'República Centro-Africana', icon: () => <Image source={require('../../../../assets/bandeiras/cf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[190], value: 'República Dominicana', icon: () => <Image source={require('../../../../assets/bandeiras/do.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[191], value: 'Reunião', icon: () => <Image source={require('../../../../assets/bandeiras/re.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[192], value: 'Romênia', icon: () => <Image source={require('../../../../assets/bandeiras/ro.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[193], value: 'Ruanda', icon: () => <Image source={require('../../../../assets/bandeiras/rw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[194], value: 'Saara Ocidental', icon: () => <Image source={require('../../../../assets/bandeiras/eh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[195], value: 'Samoa', icon: () => <Image source={require('../../../../assets/bandeiras/ws.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[196], value: 'Samoa Americana', icon: () => <Image source={require('../../../../assets/bandeiras/as.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[197], value: 'San Marino', icon: () => <Image source={require('../../../../assets/bandeiras/sm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[198], value: 'Santa Helena, Ascensão e Tristão da Cunha', icon: () => <Image source={require('../../../../assets/bandeiras/sh.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[199], value: 'Santa Lúcia', icon: () => <Image source={require('../../../../assets/bandeiras/lc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[200], value: 'Vaticano', icon: () => <Image source={require('../../../../assets/bandeiras/va.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[201], value: 'São Bartolomeu', icon: () => <Image source={require('../../../../assets/bandeiras/bl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[202], value: 'São Cristóvão e Neves', icon: () => <Image source={require('../../../../assets/bandeiras/kn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[203], value: 'São Martinho (parte francesa)', icon: () => <Image source={require('../../../../assets/bandeiras/mf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[204], value: 'São Martinho (parte holandesa)', icon: () => <Image source={require('../../../../assets/bandeiras/sx.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[205], value: 'São Pedro e Miquelon', icon: () => <Image source={require('../../../../assets/bandeiras/pm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[206], value: 'São Tomé e Príncipe', icon: () => <Image source={require('../../../../assets/bandeiras/st.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[207], value: 'São Vicente e Granadinas', icon: () => <Image source={require('../../../../assets/bandeiras/vc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[208], value: 'Senegal', icon: () => <Image source={require('../../../../assets/bandeiras/sn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[209], value: 'Serra Leoa', icon: () => <Image source={require('../../../../assets/bandeiras/sl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[210], value: 'Sérvia', icon: () => <Image source={require('../../../../assets/bandeiras/rs.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[211], value: 'Seicheles', icon: () => <Image source={require('../../../../assets/bandeiras/sc.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[212], value: 'Singapura', icon: () => <Image source={require('../../../../assets/bandeiras/sg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[213], value: 'Somália', icon: () => <Image source={require('../../../../assets/bandeiras/so.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[214], value: 'Sri Lanka', icon: () => <Image source={require('../../../../assets/bandeiras/lk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[215], value: 'Sudão', icon: () => <Image source={require('../../../../assets/bandeiras/sd.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[216], value: 'Sudão do Sul', icon: () => <Image source={require('../../../../assets/bandeiras/ss.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[217], value: 'Suécia', icon: () => <Image source={require('../../../../assets/bandeiras/se.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[218], value: 'Suíça', icon: () => <Image source={require('../../../../assets/bandeiras/ch.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[219], value: 'Suriname', icon: () => <Image source={require('../../../../assets/bandeiras/sr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[220], value: 'Svalbard e Jan Mayen', icon: () => <Image source={require('../../../../assets/bandeiras/sj.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[221], value: 'Tailândia', icon: () => <Image source={require('../../../../assets/bandeiras/th.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[222], value: 'Taiwan', icon: () => <Image source={require('../../../../assets/bandeiras/tw.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[223], value: 'Tajiquistão', icon: () => <Image source={require('../../../../assets/bandeiras/tj.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[224], value: 'Tanzânia', icon: () => <Image source={require('../../../../assets/bandeiras/tz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[225], value: 'Território Britânico do Oceano Índico', icon: () => <Image source={require('../../../../assets/bandeiras/io.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[226], value: 'Terras Austrais e Antárticas Francesas', icon: () => <Image source={require('../../../../assets/bandeiras/tf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[227], value: 'Timor-Leste', icon: () => <Image source={require('../../../../assets/bandeiras/tl.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[228], value: 'Togo', icon: () => <Image source={require('../../../../assets/bandeiras/tg.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[229], value: 'Toquelau', icon: () => <Image source={require('../../../../assets/bandeiras/tk.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[230], value: 'Tonga', icon: () => <Image source={require('../../../../assets/bandeiras/to.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[231], value: 'Trinidad e Tobago', icon: () => <Image source={require('../../../../assets/bandeiras/tt.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[232], value: 'Tunísia', icon: () => <Image source={require('../../../../assets/bandeiras/tn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[233], value: 'Turcomenistão', icon: () => <Image source={require('../../../../assets/bandeiras/tm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[234], value: 'Turquia', icon: () => <Image source={require('../../../../assets/bandeiras/tr.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[235], value: 'Tuvalu', icon: () => <Image source={require('../../../../assets/bandeiras/tv.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[236], value: 'Ucrânia', icon: () => <Image source={require('../../../../assets/bandeiras/ua.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[237], value: 'Uganda', icon: () => <Image source={require('../../../../assets/bandeiras/ug.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[238], value: 'Uruguai', icon: () => <Image source={require('../../../../assets/bandeiras/uy.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[239], value: 'Uzbequistão', icon: () => <Image source={require('../../../../assets/bandeiras/uz.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[240], value: 'Vanuatu', icon: () => <Image source={require('../../../../assets/bandeiras/vu.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[241], value: 'Venezuela', icon: () => <Image source={require('../../../../assets/bandeiras/ve.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[242], value: 'Vietnã', icon: () => <Image source={require('../../../../assets/bandeiras/vn.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[243], value: 'Wallis e Futuna', icon: () => <Image source={require('../../../../assets/bandeiras/wf.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[244], value: 'Zâmbia', icon: () => <Image source={require('../../../../assets/bandeiras/zm.png')} style={{ width: 32, height: 22 }} /> },
    { label: pais[245], value: 'Zimbábue', icon: () => <Image source={require('../../../../assets/bandeiras/zw.png')} style={{ width: 32, height: 22 }} /> }
];
return paisesComBandeiras;
}